//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel;

namespace Sovet247Admin.Models
{
    using System;
    using System.Collections.Generic;

    public partial class AdminMessage
    {
        public AdminMessage()
        {
            this.parentMessageId = 0;
        }

        public int adminMessageId { get; set; }
        public int parentMessageId { get; set; }
        [DisplayName("Отправитель")]
        public int fromUserId { get; set; }
        [DisplayName("Получатель")]
        public int toUserId { get; set; }
        [DisplayName("Тема сообщения")]
        public string subject { get; set; }
        [DisplayName("Сообщение")]
        public string message { get; set; }
        [DisplayName("Дата")]
        public System.DateTime dateCreated { get; set; }
        [DisplayName("Прочитано")]
        public bool IsHasRead { get; set; }

        public virtual User FromUser { get; set; }
        public virtual User ToUser { get; set; }
    }
}
