//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sovet247Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdminMessage
    {
        public AdminMessage()
        {
            this.AdminMessages1 = new HashSet<AdminMessage>();
        }
    
        public int adminMessageId { get; set; }
        public int parentMessageId { get; set; }
        public int fromUserId { get; set; }
        public int toUserId { get; set; }
        public string subject { get; set; }
        public string message { get; set; }
        public System.DateTime dateCreated { get; set; }
    
        public virtual ICollection<AdminMessage> AdminMessages1 { get; set; }
        public virtual AdminMessage AdminMessage1 { get; set; }
    }
}
