//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sovet247Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdminMessage
    {
        public AdminMessage()
        {
            this.parentMessageId = 0;
        }
    
        public int adminMessageId { get; set; }
        public int parentMessageId { get; set; }
        public int fromUserId { get; set; }
        public int toUserId { get; set; }
        public string subject { get; set; }
        public string message { get; set; }
        public System.DateTime dateCreated { get; set; }
        public bool IsHasRead { get; set; }
    
        public virtual User FromUser { get; set; }
        public virtual User ToUser { get; set; }
    }
}
