//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel;

namespace Sovet247Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Consultation_Statuses
    {
        public Consultation_Statuses()
        {
            this.Consultations = new HashSet<Consultation>();
        }
    
        public int ConsultationStatusId { get; set; }
        [DisplayName("Статус")]
        public string status_title { get; set; }
    
        public virtual ICollection<Consultation> Consultations { get; set; }
    }
}
