//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel;

namespace Sovet247Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Consultation_Types
    {
        public Consultation_Types()
        {
            this.Consultations = new HashSet<Consultation>();
        }
    
        public int ConsultationTypeId { get; set; }
        [DisplayName("Тип консультации")]
        public string consultation_type { get; set; }
        [DisplayName("Активен")]
        public byte active { get; set; }
    
        public virtual ICollection<Consultation> Consultations { get; set; }
    }
}
