//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sovet247Admin.Models
{
    using Microsoft.AspNet.Identity.EntityFramework;
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class ConsultationsDbContext:DbContext
    {
        public ConsultationsDbContext()
            : base("name=consultationsConnectionString")
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public virtual DbSet<AdminMessage> AdminMessages { get; set; }
        public virtual DbSet<Consultant> Consultants { get; set; }
        public virtual DbSet<Consultation_Statuses> Consultation_Statuses { get; set; }
        public virtual DbSet<Consultation_Time> Consultation_Time { get; set; }
        public virtual DbSet<Consultation_Types> Consultation_Types { get; set; }
        public virtual DbSet<Consultation> Consultations { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<Menu> Menus { get; set; }
        public virtual DbSet<Message> Messages { get; set; }
        public virtual DbSet<Profession> Professions { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Specialty> Specialties { get; set; }
        public virtual DbSet<Transaction> Transactions { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
