//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sovet247Admin.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ConsultationsDbContext : DbContext
    {
        public ConsultationsDbContext()
            : base("name=ConsultationsDbContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdminMessage> AdminMessages { get; set; }
        public virtual DbSet<Consultant> Consultants { get; set; }
        public virtual DbSet<Consultation_Statuses> Consultation_Statuses { get; set; }
        public virtual DbSet<Consultation_Time> Consultation_Time { get; set; }
        public virtual DbSet<Consultation_Types> Consultation_Types { get; set; }
        public virtual DbSet<Consultation> Consultations { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<Menu> Menus { get; set; }
        public virtual DbSet<Message> Messages { get; set; }
        public virtual DbSet<Profession> Professions { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Specialty> Specialties { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Transaction> Transactions { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
