//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sovet247Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Consultation_Time
    {
        public int consultationTimeId { get; set; }
        public Nullable<int> ConsultationId { get; set; }
        public Nullable<System.DateTime> startTime { get; set; }
        public Nullable<System.DateTime> endTime { get; set; }
        public string skypeContact { get; set; }
        public string phoneContact { get; set; }
    
        public virtual Consultation Consultation { get; set; }
    }
}
