//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sovet247Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Consultation_Types
    {
        public Consultation_Types()
        {
            this.Consultations = new HashSet<Consultation>();
        }
    
        public int ConsultationTypeId { get; set; }
        public string consultation_type { get; set; }
        public byte active { get; set; }
    
        public virtual ICollection<Consultation> Consultations { get; set; }
    }
}
