//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sovet247Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Consultant
    {
        public Consultant()
        {
            this.Consultations = new HashSet<Consultation>();
        }
    
        public int ConsultantId { get; set; }
        public int ProfessionId { get; set; }
        public Nullable<int> SpecialtyId { get; set; }
        public string specialization { get; set; }
        public int UserId { get; set; }
        public string education { get; set; }
        public string workplace { get; set; }
        public bool active { get; set; }
        public string short_resume { get; set; }
        public Nullable<decimal> comission_percent { get; set; }
        public string photo_url { get; set; }
        public string admin_comments { get; set; }
    
        public virtual User User { get; set; }
        public virtual ICollection<Consultation> Consultations { get; set; }
        public virtual Profession Profession { get; set; }
        public virtual Specialty Specialty { get; set; }
    }
}
