//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel;

namespace Sovet247Admin.Models
{
    using System;
    using System.Collections.Generic;

    public partial class Consultation
    {
        public Consultation()
        {
            this.Consultation_Time = new HashSet<Consultation_Time>();
            this.Messages = new HashSet<Message>();
            this.Transactions = new HashSet<Transaction>();
        }

        public int ConsultationId { get; set; }
        [DisplayName("Клиент")]
        public int UserId { get; set; }
        [DisplayName("Консультант")]
        public Nullable<int> ConsultantId { get; set; }
        [DisplayName("Вопрос")]
        public string subject { get; set; }
        [DisplayName("Тип консультации")]
        public int consultation_type { get; set; }
        [DisplayName("Профессия")]
        public int ProfessionId { get; set; }
        [DisplayName("Специальность")]
        public Nullable<int> SpecialtyId { get; set; }
        [DisplayName("Статус")]
        public int consultation_status { get; set; }
        [DisplayName("Дата")]
        public System.DateTime create_date { get; set; }
        [DisplayName("Дата обновления")]
        public System.DateTime update_date { get; set; }
        [DisplayName("Рейтинг")]
        public Nullable<decimal> customer_rating { get; set; }
        [DisplayName("Комментарий")]
        public string customer_comments { get; set; }
        [DisplayName("Стоимость вопроса")]
        public decimal consultation_price { get; set; }
        [DisplayName("Комментарий администратора")]
        public string admin_comments { get; set; }


        public virtual Consultant Consultant { get; set; }
        public virtual Consultation_Statuses Consultation_Statuses { get; set; }
        public virtual ICollection<Consultation_Time> Consultation_Time { get; set; }
        public virtual Consultation_Types Consultation_Types { get; set; }
        public virtual Profession Profession { get; set; }
        public virtual Specialty Specialty { get; set; }
        public virtual ICollection<Message> Messages { get; set; }
        public virtual ICollection<Transaction> Transactions { get; set; }
        public virtual User User { get; set; }
    }
}
