//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sovet247Admin.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    
    public partial class Country
    {
        public Country()
        {
            this.Users = new HashSet<User>();
        }
    
        public int CountryId { get; set; }
        [DisplayName("Код страны")]
        public string country_code { get; set; }
        [DisplayName("Наименование страны")]
        public string country_name { get; set; }
    
        public virtual ICollection<User> Users { get; set; }
    }
}
