//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sovet247Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public int MessageId { get; set; }
        public Nullable<int> ConsultationId { get; set; }
        public string message1 { get; set; }
        public Nullable<System.DateTime> added_date { get; set; }
        public string attachment { get; set; }
        public Nullable<int> UserId { get; set; }
        public byte published { get; set; }
    
        public virtual Consultation Consultation { get; set; }
        public virtual User User { get; set; }
    }
}
