//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel;

namespace Sovet247Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public int MessageId { get; set; }
        public Nullable<int> ConsultationId { get; set; }
        [DisplayName("Текст сообщения")]
        public string message1 { get; set; }
        [DisplayName("Дата")]
        public Nullable<System.DateTime> added_date { get; set; }
        [DisplayName("Вложения")]
        public string attachment { get; set; }
        [DisplayName("Автор")]
        public Nullable<int> UserId { get; set; }
        [DisplayName("Опубликован")]
        public byte published { get; set; }
    
        public virtual Consultation Consultation { get; set; }
        public virtual User User { get; set; }
    }
}
