//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sovet247Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profession
    {
        public Profession()
        {
            this.Consultations = new HashSet<Consultation>();
            this.Specialties = new HashSet<Specialty>();
            this.Consultants = new HashSet<Consultant>();
        }
    
        public int ProfessionId { get; set; }
        public string Profession_Title { get; set; }
        public bool Active { get; set; }
    
        public virtual ICollection<Consultation> Consultations { get; set; }
        public virtual ICollection<Specialty> Specialties { get; set; }
        public virtual ICollection<Consultant> Consultants { get; set; }
    }
}
