//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sovet247Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profession
    {
        public Profession()
        {
            this.Consultations = new HashSet<Consultation>();
            this.Specialties = new HashSet<Specialty>();
        }
    
        public int ProfessionId { get; set; }
        public string Profession_Title { get; set; }
        public bool Active { get; set; }
    
        public virtual ICollection<Consultation> Consultations { get; set; }
        public virtual ICollection<Specialty> Specialties { get; set; }
    }
}
