//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sovet247Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Specialty
    {
        public Specialty()
        {
            this.Consultations = new HashSet<Consultation>();
        }
    
        public int SpecialtyId { get; set; }
        public string Specialty_title { get; set; }
        public int ProfessionId { get; set; }
        public bool active { get; set; }
    
        public virtual ICollection<Consultation> Consultations { get; set; }
        public virtual Profession Profession { get; set; }
    }
}
