//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sovet247Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int TransactionId { get; set; }
        public int UserId { get; set; }
        public decimal amount { get; set; }
        public System.DateTime transactionDate { get; set; }
        public string description { get; set; }
        public Nullable<int> ConsultationId { get; set; }
    
        public virtual Consultation Consultation { get; set; }
        public virtual User User { get; set; }
    }
}
