//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel;

namespace Sovet247Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int TransactionId { get; set; }
        [DisplayName("Пользователь")]
        public int UserId { get; set; }
        [DisplayName("Сумма")]
        public decimal amount { get; set; }
        [DisplayName("Дата операции")]
        public System.DateTime transactionDate { get; set; }
        [DisplayName("Описание")]
        public string description { get; set; }
        [DisplayName("Консультация")]
        public Nullable<int> ConsultationId { get; set; }
        [DisplayName("Подтверждена администратором")]
        public bool isApproved { get; set; }

        public virtual Consultation Consultation { get; set; }
        public virtual User User { get; set; }
    }
}
