//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sovet247Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Consultants = new HashSet<Consultant>();
            this.Messages = new HashSet<Message>();
            this.Transactions = new HashSet<Transaction>();
            this.AdminMessages = new HashSet<AdminMessage>();
            this.AdminMessages1 = new HashSet<AdminMessage>();
            this.Consultations = new HashSet<Consultation>();
        }
    
        public int UserId { get; set; }
        public string nickname { get; set; }
        public string password { get; set; }
        public string email { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public string middlename { get; set; }
        public string street_address { get; set; }
        public string city { get; set; }
        public Nullable<int> CountryId { get; set; }
        public string zip { get; set; }
        public string state { get; set; }
        public string phone { get; set; }
        public short wants_newsletter { get; set; }
        public string alternate_contacts { get; set; }
        public string comments { get; set; }
        public short can_publish_questions { get; set; }
        public int RoleId { get; set; }
    
        public virtual ICollection<Consultant> Consultants { get; set; }
        public virtual Country Country { get; set; }
        public virtual ICollection<Message> Messages { get; set; }
        public virtual Role Role { get; set; }
        public virtual ICollection<Transaction> Transactions { get; set; }
        public virtual ICollection<AdminMessage> AdminMessages { get; set; }
        public virtual ICollection<AdminMessage> AdminMessages1 { get; set; }
        public virtual ICollection<Consultation> Consultations { get; set; }
    }
}
